server:
  port: 8888
  
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anuj-mehra/spring-cloud-config-server
          skipSslValidation: true